### ISSUE TITLE
oada_base_uri should reflect the server address

### ISSUE THREAD

**Issue by wang701** [OADA/oada-api-server#12]
After sending a GET request to
`https://vip4.ecn.purdue.edu:3000/.well-known/oada-configuration`

,this is the response I get:

`
{
  "well_known_version": "1.0.0",
  "oada_base_uri": "https://localhost:3000/",
  "scopes_supported": [
    {
      "name": "oada.all.1",
      "read+write": true
    }
  ],
  "authorization_endpoint": "https://vip4.ecn.purdue.edu:3000/auth",
  "token_endpoint": "https://vip4.ecn.purdue.edu:3000/token",
  "registration_endpoint": "https://vip4.ecn.purdue.edu:3000/register",
  "token_endpoint_auth_signing_alg_values_supported": [
    "RS256"
  ]
}
`

I am not entirely certain but I think the OADA server should be able to change the value of "oada_base_uri" to something like `vip4.ecn.purdue.edu`.

**Comment by aultac** [comment]
You can set the server name in the config for the api server.
