### ISSUE TITLE
Tests throw errors and still say they pass

### ISSUE THREAD

**Issue by awlayton** [OADA/oada-api-server#3]
It happens to atleast one of them, probably more.

[Here](https://travis-ci.org/OADA/oada-api-server/jobs/79416298#L835-L859) is where it happened on Travis.

**Comment by aultac** [comment]
I will look into it, but that particular test in Travis should pass in the event of that particular exception, I believe.  rev-graph should work regardless of whether the memory-db is able to persist to the disk.  I'm going to move ../data back into the repo itself to avoid this problem, though.  Maybe it should actually just override the data directory in the test itself so it has more control over what's in the persisted database.
